spring:
  application:
    name: Auth Server
  profiles:
    active:
      - dev
      - localhost
  jpa:
    repositories:
      enabled: true
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
#H2
  datasource:
    url: jdbc:h2:~/test
    name: test
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2


server:
  port: 9095