spring:
  application:
    name: Spring raw template
  profiles:
    active:
      - h2
      - localhost
      #      - mysql  #when mysql


logging:
  level:
    org.springframework: INFO
  path: logs
liquibase:
  change-log: classpath:database/base-db-changelog.xml

server:
  port: 9095



