spring:
  application:
    name: Spring raw template
  profiles:
    active:
      - h2
#      - mysql  #when mysql
      - localhost

logging:
  level:
    org.springframework: INFO
#liquibase:
#  change-log: classpath:database/changelog/db-changelog.xml uncomment when using liquibase - db-changelog.xml in resources

server:
  port: 9095



